### ISSUE TITLE
This script doesn't work

### ISSUE THREAD

**Issue by jmcastel** [the4dpatrick/find-any-email#8]
Hello.

It 's not working...

Could you update plz ?

Tks

**Comment by grinono** [comment]
their will come no update because of the oath part they implemented. 

Their is also a Chrome extension that automates this process.  Not possible in bulk, but for a few adreses per day it works great. 
 
https://chrome.google.com/webstore/detail/find-any-email-on-linkedi/fekiadmepikilfpklicpiedpggbflnmc?hl=en-US&authuser=2

**Comment by the4dpatrick** [comment]
There are no current plans to update this script
